# Generated by Django 3.0.2 on 2020-01-05 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20200105_2016'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='personal_description',
            field=models.TextField(default=''),
        ),
    ]
