# Generated by Django 3.0.2 on 2020-01-07 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20200107_2326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='personal_description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='user',
            name='verification_token',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='verified',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
