# Generated by Django 3.0.2 on 2020-01-03 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Test', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='test_topic',
            field=models.CharField(max_length=50),
        ),
    ]
